networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    tty: true
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports: 
      - "80:80"
    env_file:
      - .env  
    networks: 
      - $NETWORK
      - $BACKEND
    depends_on:
      - backend

  database:
    image: mongo
    container_name: $MONGODB_HOST_NAME
    command: "--auth & /bin/sh -c 'chmod +x /docker-entrypoint-initdb.d/mongo-init.sh & /bin/bash /docker-entrypoint-initdb.d/mongo-init.sh'"
    restart: always
    env_file:
      - .env
    tty: true
    environment:
      MONGO_INITDB_DATABASE: $MONGODB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_ROOT_PASSWORD
      MONGO_INITDB_USERNAME: $MONGODB_USER
      MONGO_INITDB_PASSWORD: $MONGODB_PASSWORD
      TZ: America/Sao_Paulo
    volumes:
      - ./data/mongodb/db:/data/db
      - ./data/mongodb/logs:/var/log/mongodb
      - ./data/mongodb/entrypoint/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - "$MONGODB_PORT:27017"
    networks:
      - $BACKEND
  
  mongo-express:
    image: mongo-express
    container_name: $EXPRESS_MONGO_HOST_NAME
    restart: always
    ports:
      - "$EXPRESS_MONGO_PORT:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: $EXPRESS_MONGO_ADMIN_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $EXPRESS_MONGO_ADMIN_PASSWORD
      ME_CONFIG_BASICAUTH_USERNAME: $EXPRESS_MONGO_BASIC_USERNAME
      ME_CONFIG_BASICAUTH_PASSWORD: $EXPRESS_MONGO_BASIC_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_ROOT_USER:$MONGODB_ROOT_PASSWORD@$MONGODB_HOST_NAME:$MONGODB_PORT/
    depends_on:
      - database
    networks:
      - $BACKEND

  backend:
    build: 
      context: backend
    container_name: backend
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "$BACKEND_PORT:8080"
    depends_on:
      - database
    networks:
      - $BACKEND