networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    tty: true
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports: 
      - "80:80"
    env_file:
      - .env  
    networks: 
      - frontend
      - backend
    depends_on:
      - backend

  database:
    image: mongo
    container_name: taxi_database
    command: "--auth & /bin/sh -c 'chmod +x /docker-entrypoint-initdb.d/mongo-init.sh & /bin/bash /docker-entrypoint-initdb.d/mongo-init.sh'"
    restart: always
    env_file:
      - .env
    tty: true
    environment:
      MONGO_INITDB_DATABASE: taxi
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: lVlY0rM3PwS5U2cP
      MONGO_INITDB_USERNAME: rommel
      MONGO_INITDB_PASSWORD: B3QA9BW295t6ZmVs
      TZ: America/Sao_Paulo
    volumes:
      - ./data/mongodb/db:/data/db
      - ./data/mongodb/logs:/var/log/mongodb
      - ./data/mongodb/entrypoint/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    ports:
      - "$27017:27017"
    networks:
      - backend
  
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1YmOP7S2ZwEuh0vn
      ME_CONFIG_BASICAUTH_USERNAME: rommel
      ME_CONFIG_BASICAUTH_PASSWORD: hD7RIgdG7ovUmuyY
      ME_CONFIG_MONGODB_URL: mongodb://rommel:B3QA9BW295t6ZmVs@taxi_database:27017
    depends_on:
      - database
    networks:
      - backend

  backend:
    build: 
      context: backend
    container_name: backend
    restart: always
    tty: true
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend